### ISSUE TITLE
Is there any admin/control panel to operate this ?

### ISSUE THREAD

**Issue by muhammadarsalansiddiqui** [alexk99/the_router#11]

**Comment by alexk99** [comment]
A web interface is going to be ready in late 2022.
Currently, there is a CLI to operate BisonRouter.

**Comment by muhammadarsalansiddiqui** [comment]
hi Alex, I want to contribute to it, I have done installation by using documentation.
I'm done having patches now what's the next step how to download the router (documentation says me to contact you) ?

**Comment by muhammadarsalansiddiqui** [comment]
@alexk99 , are you available ?

**Comment by FDN2018** [comment]
Yes you can call me at whatsapp +919599521741 and skype- amit4120Get Outlook for Android
