### ISSUE TITLE
Проблема в Убунту

### ISSUE THREAD

**Issue by heupo21** [alexk99/the_router#3]
вот лог запуска:
Nov 29 14:54:26 dpsk-test the_router[1520]: EAL: Detected 4 lcore(s)
Nov 29 14:54:26 dpsk-test the_router[1520]: EAL: No free hugepages reported in hugepages-1048576kB
Nov 29 14:54:26 dpsk-test the_router[1520]: EAL: Probing VFIO support...
Nov 29 14:54:27 dpsk-test the_router[1520]: PMD: bnxt_rte_pmd_init() called for (null)
Nov 29 14:54:27 dpsk-test the_router[1520]: EAL: PCI device 0000:05:00.0 on NUMA socket 0
Nov 29 14:54:27 dpsk-test the_router[1520]: EAL:   probe driver: 8086:1521 rte_igb_pmd
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: system has 4 enabled lcores
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define NPF_ENABLED 1
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define NPF_ENABLED_VEC 1
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define DONT_SLEEP 1
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define L2_DYNAMIC_VIF_ENABLED 1
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define PBR 1
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define PRH_DEBUG 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define PRH_RESIZABLE_DEBUG 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define PRINT_DEBUG 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define ROUTER_DEBUG 1
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define NPF_DEBUG 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #define RETRY_TX_BURST 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Loading the startup part of configuration file '/etc/router.conf'...
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: router configuration file '/etc/router.conf' sucessfully loaded
Nov 29 14:54:27 dpsk-test kernel: [   98.851035] KNI: Single kernel thread for all KNI devices
Nov 29 14:54:27 dpsk-test kernel: [   98.851055] KNI: /dev/kni opened
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: active worker lcores 3
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Initializing 3 tx queues at each port
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: port #0 driver name rte_igb_pmd
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Initializing port 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #011creating queues: rx 3, tx 3
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: port 0: rss hash function = ETH_RSS_IP
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #011mac address:A0:36:9F:46:89:30
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: port_id 0 txconf: hthresh 1, pthresh 8, wthresh 16, tx_free_thresh 0, tx_rs_thresh 0, txq_flags 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #011tx queue lcore 1, port_id 0, queue_id 0, socket_id 0, num tx desc 512
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #011tx queue lcore 2, port_id 0, queue_id 1, socket_id 0, num tx desc 512
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: #011tx queue lcore 3, port_id 0, queue_id 2, socket_id 0, num tx desc 512
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Allocated mbuf pool on socket 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Allocated indirect mbuf pool on socket 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Allocated ctrl mbuf pool
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Initializing rx queues on lcore 0:
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Initializing rx queues on lcore 1:
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: port 0, queue 0, socket 0, num rx desc 128
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Initializing rx queues on lcore 2:
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: port 0, queue 1, socket 0, num rx desc 128
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Initializing rx queues on lcore 3:
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: port 0, queue 2, socket 0, num rx desc 128
Nov 29 14:54:27 dpsk-test the_router[1520]: PMD: eth_igb_start(): lsc won't enable because of no intr multiplex
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Checking link status...
Nov 29 14:54:28 dpsk-test the_router[1520]: ROUTER: Checking link status - done
Nov 29 14:54:28 dpsk-test the_router[1520]: ROUTER: Port 0 Link Down
Nov 29 14:54:28 dpsk-test kernel: [   99.238804] KNI: /dev/kni closed

подскажите с чем может быть связано то, что софтина не запускается ? Куда копать.

**Comment by alexk99** [comment]
Привет. А подскажи, какая это версия? я в последних lsc выключил. А то у тебя в логе есть
строчка 
Nov 29 14:54:27 dpsk-test the_router[1520]: PMD: eth_igb_start(): lsc won't enable because of no intr multiplex
Это не критично, но все же.

И покажи пожалуйста еще конфиг 
/etc/router.conf
вывод  grep -i huge /proc/meminfo
и версию ядра

**Comment by alexk99** [comment]
а еще port 0, это какая сетевая карта, модель?

**Comment by alexk99** [comment]
кажется вот причина, в самом начале лога, что-то сразу и не заметил
EAL: No free hugepages reported in hugepages-1048576kB
надо проверить, настройки Hugepages, т.е. все вопросы, которые я задал актуальны, особенно вывод meminfo

**Comment by heupo21** [comment]
startup {
          sysctl set mbuf 8192
          port 0 mtu 1500 tpid 0x8100 state enabled
#         port 2 mtu 1500 tpid 0x8100 state enabled
#         port 3 mtu 1500 tpid 0x8100 state enabled

          rx_queue port 0 queue 0 lcore 1
          rx_queue port 0 queue 1 lcore 2
          rx_queue port 0 queue 2 lcore 3

          sysctl set global_packet_counters 1
        }

        runtime {
        vif add name p1 port 0 type untagged
        ip addr add 85.234.20.115/24 dev p1

        npf load "/etc/npf.conf"
        }

root@dpsk-test:/usr/src/dpdk-16.07# $RTE_SDK/tools/dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
0000:05:00.0 'I350 Gigabit Network Connection' drv=igb_uio unused=igb

root@dpsk-test:/usr/src/dpdk-16.07# grep -i huge /proc/meminfo
AnonHugePages:      6144 kB
HugePages_Total:    2560
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
памяти всего 6Гб, больше нету ))) 

root@dpsk-test:/usr/src/dpdk-16.07# uname -a
Linux dpsk-test 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

а при менее чем 3к страниц работать не будет? ) меня поначалу тоже смутила ругань на свободные страницы. после ребута они все свободны, но ошибка та же с lsc.

установка проводилась по этому мануалу: https://github.com/alexk99/the_router/blob/master/ubuntu_install.md
соответственно все скачано по тем же ссылкам. 

ну и плюс не все либы ставятся куда надо с нужными именами. при первом запуске матюгается на отсутствие библиотек, приходилось линковать и копировать.

**Comment by heupo21** [comment]
проц - Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
версия софта - для старых Ксеонов http://therouter.net/downloads/the_router.latest.6cores.dpdk.16.07.tar.gz

**Comment by alexk99** [comment]
По поводу памяти. Похоже, все-таки с памятью все ок. Иначе бы не были бы успешно созданы
пулы объектов, например вот эти:
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Allocated mbuf pool on socket 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Allocated indirect mbuf pool on socket 0
Nov 29 14:54:27 dpsk-test the_router[1520]: ROUTER: Allocated ctrl mbuf pool

Вывод про 1g страницы не критичен, я ошибся, посчитав, что это причина незапуска.
EAL: No free hugepages reported in hugepages-1048576kB

Сколько нужно памяти the_router я никогда не считал, но думаю, что он и гигабайт не использует. Поэтому, 3k 2мбайтных huge страниц - совершенно не обязательно.

Ошибка с lsc абсолютно некртична. Эта фукниция никак не используется. Она постоянно
была в логах раньше и при успешных запусках. В нескольких последних версиях я ее выключил
из инициализации. Просто версия для "старых ксеонов" давно не обновлялась. Я сегодня вечером
выложу последнюю версию. Заодно добавлю еще несколько info выводов в сислог, чтобы понять точнее место, на котором происходит сбой.

А ты пробовал обычную версию (http://therouter.net/downloads/the_router.latest.6cores.dpdk.16.07.tar.gz) запускать ?

И последний вопрос, а программа успешно завершается, не крашится? 
Если задать sysctl переменную
kernel.core_pattern = /tmp/core_%e.%p
будет крешдамп создаваться?

**Comment by alexk99** [comment]
а, забыл упомянуть HugePages_Free: 0 - после первого запуска нормально. Только после перезагрузки они всегда свободны.

**Comment by heupo21** [comment]
Собрал систему на другом сервере:
Intel(R) Xeon(R) CPU           E5540  @ 2.53GHz
MemTotal:       12294660 kB
после задания 3к страниц, сообщение о нехватке памяти пропало. 
дамп не создается. видимо завершается нормально.
В остальном лог такой же. 

попробую другую версию, отпишусь.
по поводу библиотек, пришлось создавать ссылки:

ln -s /usr/lib64/libnpf.so.0.0.0 /usr/lib/libnpfkern.so.0
ln -s /usr/local/lib/libpcap.so.1.5.3 /usr/lib/libpcap.so.1
ln -s /usr/local/lib/libcityhash.so.0.0.0 /usr/lib/libcityhash.so.0
ln -s /usr/local/lib/libprop.so.0.0.13 /usr/lib/libprop.so.0

**Comment by heupo21** [comment]
при попытки запуска другой версии получаю такое:
root@dpdk-test:/usr/local/sbin# /usr/local/sbin/router_run.sh /etc/router.conf
ERROR: This system does not support "AES".
Please check that RTE_MACHINE is set correctly.

**Comment by alexk99** [comment]
Обновил версию для ксеонов. а0.16 - последняя. Ссылки в https://github.com/alexk99/the_router/blob/master/ubuntu_install.md

Добавил логгирование еще нескольких шагов процесса инициализации. Теперь точнее можно будет сказать, что происходит. И в этой версии не будет lsc, чтобы не раздражала эта ошибка в логе.

По поводу путей, я думаю, лучше не ссылки создавать, а обновлять пути поиска библиотек.
Этот пункт был у меня в черновике, забыл добавить в финальную доку.
Поправил, вот этот раздел 
https://github.com/alexk99/the_router/blob/master/ubuntu_install.md#update-system-library-paths

> после задания 3к страниц, сообщение о нехватке памяти пропало.
> дамп не создается. видимо завершается нормально.
Вот это сообщение?
EAL: No free hugepages reported in hugepages-1048576kB

Это не совсем нехватка, это просто констатация факта, что гиговых страниц не разерверивано.
Ты резервируешь 2 мбайтные страницы, не 1гигабайтные страницы ведь? Просто процессор у тебя, похоже, поддерживает и гиговые huge страницы тоже.

**Comment by alexk99** [comment]
Еще, если не сложно, а попробуй запустить какую-нибудь тестовую программу из dpdk дистрибутива.
Например, test-pmd.
  cd $RTE_SDK/app/test-pmd/
  make

и запускаешь testpmd потом
ей нужно будет указать базовые dpdk параметры -w -n -l
http://dpdk.org/doc/guides/testpmd_app_ug/index.html

**Comment by alexk99** [comment]
Еще, раз программа не падает, а нормально завершается, то можно попробовать отследить вывозы завершения с помощью gdb. Добавляешь в файл запуска прямо перед the_router
gdb --args. Должно получится gdb --args the_router ...
Дальше в самом gdb
catch syscall 60
catch syscall 231
break abort
run
если кто-то действительно вызывает еxit, выполнение должно остановиться, выдав что-нибудь типа
Catchpoint 3 (call to syscall 231), 0x00007ffff66eb629 in _exit () from /lib64/libc.so.6

затем выполни команду
bt
и вывод мне

**Comment by heupo21** [comment]
> Ты резервируешь 2 мбайтные страницы, не 1гигабайтные страницы ведь? Просто процессор у тебя, похоже, поддерживает и гиговые huge страницы тоже.
да

> gdb --args. Должно получится gdb --args the_router ...
> Дальше в самом gdb
> catch syscall 60
> catch syscall 231
> break abort
> run
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/local/sbin/the_router /usr/local/sbin/router_run.sh
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5e50700 (LWP 42661)]
[New Thread 0x7ffff564f700 (LWP 42662)]
[New Thread 0x7ffe73bff700 (LWP 42663)]
[New Thread 0x7ffe733fe700 (LWP 42664)]
/usr/local/sbin/the_router: symbol lookup error: /usr/local/sbin/the_router: undefined symbol: npf_sysinit
Thread 1 "the_router" hit Catchpoint 2 (call to syscall fgetxattr), 0x00007ffff7df2598 in __GI__exit (status=127) at ../sysdeps/unix/sysv/linux/_exit.c:31
31      ../sysdeps/unix/sysv/linux/_exit.c: No such file or directory.

**Comment by heupo21** [comment]
testpmd
root@dpdk-test:/usr/src/dpdk-16.07/x86_64-native-linuxapp-gcc/app# $RTE_SDK/tools/dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
0000:02:00.0 'I350 Gigabit Network Connection' drv=igb_uio unused=igb
0000:02:00.1 'I350 Gigabit Network Connection' drv=igb_uio unused=igb

Network devices using kernel driver
===================================
0000:01:00.0 '82576 Gigabit Network Connection' if=enp1s0f0 drv=igb unused=igb_uio 
0000:01:00.1 '82576 Gigabit Network Connection' if=enp1s0f1 drv=igb unused=igb_uio 
0000:03:00.0 '82576 Gigabit Network Connection' if=enp3s0f0 drv=igb unused=igb_uio 
0000:03:00.1 '82576 Gigabit Network Connection' if=enp3s0f1 drv=igb unused=igb_uio 
0000:06:00.0 '82574L Gigabit Network Connection' if=enp6s0 drv=e1000e unused=igb_uio *Active*
0000:07:00.0 '82574L Gigabit Network Connection' if=enp7s0 drv=e1000e unused=igb_uio 

Other network devices
=====================
<none>
root@dpdk-test:/usr/src/dpdk-16.07/x86_64-native-linuxapp-gcc/app# ./testpmd
Configuring Port 0 (socket 0)
Port 0: A0:36:9F:2B:33:56
Configuring Port 1 (socket 0)
Port 1: A0:36:9F:2B:33:57
Checking link statuses...
Port 0 Link Up - speed 1000 Mbps - full-duplex
Port 1 Link Up - speed 1000 Mbps - full-duplex
Done
No commandline core given, start packet forwarding
io packet forwarding - ports=2 - cores=1 - streams=2 - NUMA support disabled, MP over anonymous pages disabled
Logical Core 1 (socket 0) forwards packets on 2 streams:
  RX P=0/Q=0 (socket 0) -> TX P=1/Q=0 (socket 0) peer=02:00:00:00:00:01
  RX P=1/Q=0 (socket 0) -> TX P=0/Q=0 (socket 0) peer=02:00:00:00:00:00

  io packet forwarding - CRC stripping disabled - packets/burst=32
  nb forwarding cores=1 - nb forwarding ports=2
  RX queues=1 - RX desc=128 - RX free threshold=32
  RX threshold registers: pthresh=8 hthresh=8 wthresh=4
  TX queues=1 - TX desc=512 - TX free threshold=0
  TX threshold registers: pthresh=8 hthresh=1 wthresh=16
  TX RS bit threshold=0 - TXQ flags=0x0
Press enter to exit

Telling cores to stop...
Waiting for lcores to finish...

  ---------------------- Forward statistics for port 0  ----------------------
  RX-packets: 22             RX-dropped: 0             RX-total: 22
  TX-packets: 22             TX-dropped: 0             TX-total: 22
  ----------------------------------------------------------------------------

  ---------------------- Forward statistics for port 1  ----------------------
  RX-packets: 22             RX-dropped: 0             RX-total: 22
  TX-packets: 22             TX-dropped: 0             TX-total: 22
  ----------------------------------------------------------------------------

  +++++++++++++++ Accumulated forward statistics for all ports+++++++++++++++
  RX-packets: 44             RX-dropped: 0             RX-total: 44
  TX-packets: 44             TX-dropped: 0             TX-total: 44
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Done.

Shutting down port 0...
Stopping ports...
Done
Closing ports...
Done

Shutting down port 1...
Stopping ports...
Done
Closing ports...
Done

Bye...

root@dpdk-test:/usr/src/dpdk-16.07/x86_64-native-linuxapp-gcc/app# ./testpmd  -w 0000:02:00.0 -w 0000:02:00.1 -n3 -l 1,2,3
Configuring Port 0 (socket 0)
Port 0: A0:36:9F:2B:33:56
Configuring Port 1 (socket 0)
Port 1: A0:36:9F:2B:33:57
Checking link statuses...
Port 0 Link Up - speed 1000 Mbps - full-duplex
Port 1 Link Up - speed 1000 Mbps - full-duplex
Done
No commandline core given, start packet forwarding
io packet forwarding - ports=2 - cores=1 - streams=2 - NUMA support disabled, MP over anonymous pages disabled
Logical Core 2 (socket 0) forwards packets on 2 streams:
  RX P=0/Q=0 (socket 0) -> TX P=1/Q=0 (socket 0) peer=02:00:00:00:00:01
  RX P=1/Q=0 (socket 0) -> TX P=0/Q=0 (socket 0) peer=02:00:00:00:00:00

  io packet forwarding - CRC stripping disabled - packets/burst=32
  nb forwarding cores=1 - nb forwarding ports=2
  RX queues=1 - RX desc=128 - RX free threshold=32
  RX threshold registers: pthresh=8 hthresh=8 wthresh=4
  TX queues=1 - TX desc=512 - TX free threshold=0
  TX threshold registers: pthresh=8 hthresh=1 wthresh=16
  TX RS bit threshold=0 - TXQ flags=0x0
Press enter to exit

Telling cores to stop...
Waiting for lcores to finish...

  ---------------------- Forward statistics for port 0  ----------------------
  RX-packets: 77             RX-dropped: 0             RX-total: 77
  TX-packets: 76             TX-dropped: 0             TX-total: 76
  ----------------------------------------------------------------------------

  ---------------------- Forward statistics for port 1  ----------------------
  RX-packets: 76             RX-dropped: 0             RX-total: 76
  TX-packets: 77             TX-dropped: 0             TX-total: 77
  ----------------------------------------------------------------------------

  +++++++++++++++ Accumulated forward statistics for all ports+++++++++++++++
  RX-packets: 153            RX-dropped: 0             RX-total: 153
  TX-packets: 153            TX-dropped: 0             TX-total: 153
  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Done.

Shutting down port 0...
Stopping ports...
Done
Closing ports...
Done

Shutting down port 1...
Stopping ports...
Done
Closing ports...
Done

Bye...

**Comment by heupo21** [comment]
лог the_router
c  1 08:46:30 dpdk-test the_router[42818]: EAL: Detected 4 lcore(s)
Dec  1 08:46:30 dpdk-test the_router[42818]: EAL: Probing VFIO support...
Dec  1 08:46:31 dpdk-test the_router[42818]: PMD: bnxt_rte_pmd_init() called for (null)
Dec  1 08:46:31 dpdk-test the_router[42818]: EAL: PCI device 0000:02:00.0 on NUMA socket -1
Dec  1 08:46:31 dpdk-test the_router[42818]: EAL:   probe driver: 8086:1521 rte_igb_pmd
Dec  1 08:46:31 dpdk-test the_router[42818]: EAL: PCI device 0000:02:00.1 on NUMA socket -1
Dec  1 08:46:31 dpdk-test the_router[42818]: EAL:   probe driver: 8086:1521 rte_igb_pmd
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: system has 4 enabled lcores
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define NPF_ENABLED 1
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define NPF_ENABLED_VEC 1
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define DONT_SLEEP 1
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define L2_DYNAMIC_VIF_ENABLED 1
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define PBR 1
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define PRH_DEBUG 0
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define PRH_RESIZABLE_DEBUG 0
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define PRINT_DEBUG 0
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define ROUTER_DEBUG 1
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define NPF_DEBUG 0
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: #define RETRY_TX_BURST 0
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Loading the startup part of configuration file '/etc/router.conf'...
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: router configuration file '/etc/router.conf' successfully loaded
Dec  1 08:46:31 dpdk-test kernel: [81545.568996] KNI: Single kernel thread for all KNI devices
Dec  1 08:46:31 dpdk-test kernel: [81545.569016] KNI: /dev/kni opened
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: active worker lcores 3
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Initializing 3 tx queues at each port
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: port #0 driver name rte_igb_pmd
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Initializing port 0
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER:    creating queues: rx 3, tx 3
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER:    port 0: rss hash function = ETH_RSS_IP
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER:    mac address:A0:36:9F:2B:33:56
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER:    port_id 0 txconf: hthresh 1, pthresh 8, wthresh 16, tx_free_thresh 0, tx_rs_thresh 0, txq_flags 0
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER:    tx queue lcore 1, port_id 0, queue_id 0, socket_id 0, num tx desc 512
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER:    tx queue lcore 2, port_id 0, queue_id 1, socket_id 0, num tx desc 512
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER:    tx queue lcore 3, port_id 0, queue_id 2, socket_id 0, num tx desc 512
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: port #1 driver name rte_igb_pmd
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Skipping disabled port 1
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Allocated mbuf pool on socket 0
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Allocated indirect mbuf pool on socket 0
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Allocated ctrl mbuf pool
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Initializing rx queues on lcore 0:
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Initializing rx queues on lcore 1:
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER:    port 0, queue 0, socket 0, num rx desc 128
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Initializing rx queues on lcore 2:
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER:    port 0, queue 1, socket 0, num rx desc 128
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Initializing rx queues on lcore 3:
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER:    port 0, queue 2, socket 0, num rx desc 128
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: lcore 0: initializing dhcp relay
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: lcore 0: dhcp relay initialization is complete
Dec  1 08:46:31 dpdk-test the_router[42818]: ROUTER: Checking link status...
Dec  1 08:46:32 dpdk-test the_router[42818]: ROUTER: Checking link status - done
Dec  1 08:46:32 dpdk-test the_router[42818]: ROUTER: Port 0 Link Down
Dec  1 08:46:32 dpdk-test the_router[42818]: ROUTER: lcore 0: initializing NPF
Dec  1 08:46:32 dpdk-test kernel: [81545.953104] KNI: /dev/kni closed

**Comment by alexk99** [comment]
lcore 0: initializing NPF --  и привет. Что-то NPF не нравится. это сторонняя библиотека. я ее код знаю достаточно хорошо, но все же не идеально.

В gdb после остановки ты, похоже, забыл сделать команду bt, да? Не видно списка обратных вызовов просто или она ничего не выдала?

А ты можешь дать ssh доступ на машину? если да, то пиши на почту kiselev99@gmail.com

**Comment by heupo21** [comment]
похоже что да, забыл. данные выслал на мыло

**Comment by alexk99** [comment]
Misleading links were the cause of the problem and prevent the_router from starting.

root@dpdk-test:/usr/src/npf/src/kern# ls -l /usr/lib/libnpf*
lrwxrwxrwx 1 root root 26 ноя 30 11:27 /usr/lib/libnpfkern.so.0 -> /usr/lib64/libnpf.so.0.0.0
lrwxrwxrwx 1 root root 15 дек  1 08:18 /usr/lib/libnpf.so.0 -> libnpfkern.so.0

Closed.
