### ISSUE TITLE
No Code in Project Repo

### ISSUE THREAD

**Issue by techhelper1** [alexk99/the_router#5]
What's the point of having a repo with a bunch of tutorials and benchmarks if there is no source code to go along with it?

**Comment by alexk99** [comment]
It's not an open source project. But you are welcome to use an already compiled binary.

**Comment by techhelper1** [comment]
Then what's the point of having a repo without code? You're making the Gandi packet journey more popular in this case.

**Comment by fcqpl** [comment]
Where is source code?
