### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by 31337Ghost** [alexk99/the_router#6]
Есть ли у вас наработки по запуску в контейнере? Или может быть у вас есть видение что в контейнере точно не заработает и даже пробовать не стоит?

**Comment by alexk99** [comment]
ничего не могу сказать про контейнеры.
софт в первую очередь предназначен
для запуска под linux на bare metal.

**Comment by 31337Ghost** [comment]
Попробовал поднять так https://github.com/31337Ghost/dpdk-router/blob/master/Dockerfile получил 
`Illegal instruction (core dumped)`

на bare metal пока нет возможности

**Comment by alexk99** [comment]
текущей сборке нужна поддержка avx инструкций, поэтому такая ошибка.

можно попробовать вот эту сборку под xeon l5506.
http://therouter.net/downloads/the_router.6cores.dpdk.17.11.1.pppoe.intel_westmere.pppoe_a0.18.tar.gz
если не подойдет, то я могу сделать, под этот конкретный процессор.

**Comment by 31337Ghost** [comment]
по предложенной ссылке на L5506 не пошла, та же ошибка

**Comment by alexk99** [comment]
напишите мне пожалуйста в почту, а то уже офтоп
