### ISSUE TITLE
NPF compilation failure

### ISSUE THREAD

**Issue by victordetoni** [alexk99/the_router#8]
Error to the compile npf in ubuntu 20.04:

Step:

Install NPF

Clone NPF

 git clone -b conn_limits https://github.com/alexk99/npf
Download city.h, then

 cp city.h /usr/local/include/
Run the following commands:

 cd npf/src	
 cd libnpf/net
 rm ./npf.h
 ln -s ../../kern/npf.h npf.h		
 cd ../..
 
 export DESTDIR=/
 export LIBDIR=/usr/lib64
 export INCDIR=/usr/local/include
 export MANDIR=/usr/local
 make
 make install

root@victor:~/npf/src# make
make -j 1 -C kern lib
make[1]: Entering directory '/root/npf/src/kern'
libtool --mode=compile --tag CC cc -std=gnu99 -O3 -Wall -Wextra -Werror -flto -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -I stand -D_NPF_STANDALONE  -D__RCSID\(x\)= -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused -DNPF_CONNMAP_EFFICIENT_CUCKOO -fvisibility=hidden -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE -c npf.c
libtool: compile:  cc -std=gnu99 -O3 -Wall -Wextra -Werror -flto -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -I stand -D_NPF_STANDALONE "-D__RCSID(x)=" -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused -DNPF_CONNMAP_EFFICIENT_CUCKOO -fvisibility=hidden -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE -c npf.c  -fPIC -DPIC -o .libs/npf.o
In file included from npf.h:45,
                 from npf_impl.h:61,
                 from npf.c:48:
stand/npf_stand.h: In function ‘npfkern_pthread_create’:
stand/npf_stand.h:207:39: error: cast between incompatible function types from ‘void (*)(void *)’ to ‘void * (*)(void *’ [-Werror=cast-function-type]
  207 |  return pthread_create(&l->thr, NULL, (void *(*)(void *))func, arg);
      |                                       ^
cc1: all warnings being treated as errors
make[1]: *** [Makefile:156: npf.lo] Error 1
make[1]: Leaving directory '/root/npf/src/kern'
make: *** [Makefile:4: all] Error 2

**Comment by alexk99** [comment]
What gcc version are you using?

**Comment by victordetoni** [comment]
victor@victor:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-10ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)

**Comment by alexk99** [comment]
One way to avoid this error is to switch to ubuntu 18. Or you could change NPF's Makefile and add some gcc options to turn off the following gcc behavior:
