### ISSUE TITLE
Is the_router suitable for a home?

### ISSUE THREAD

**Issue by bobobo1618** [alexk99/the_router#9]
The Swiss ISP Init7 recently [started offering](https://blog.init7.net/de/neue-infrastruktur/) 25Gbps internet to its customers. 

This is wonderful but there is currently very little hardware available that supports this use-case at a price regular people can afford. 

Init7 currently offers the MikroTik CCR2004-1G-12S +2XS but this is barely able to keep up in the best of circumstances. 

Would the_router running on say a mini-ITX PC with an Intel XXV710 NIC or two be a good fit?

**Comment by alexk99** [comment]
Hello. yes, it would. However, TheRouter is commercial software, its licence prices are not very friendly for home users.

**Comment by bobobo1618** [comment]
Don't suppose there's any interest in altering that? Perhaps offering a stripped-down edition without advanced features?

**Comment by alexk99** [comment]
Well, I haven't seen any interest so far except your case.
